### ISSUE TITLE
[BUG]: Collect wrong .vue file when components used with vue router (router-view)

### ISSUE THREAD

**Issue by loganbeast** [BerniWittmann/vue-unused-components-checker#17]

**Comment by BerniWittmann** [comment]
@loganbeast Can you provide more info on how you are importing your components? 

In #16 other users already found that the following import is creating false positives `component: () => import( /* webpackChunkName: "event_create" */ "../views/EventCreate.vue" ) },`, which i will try to fix as soon as i get to it
